owner: chiang # GitHub username
repo: mtr # GitHub repository name
sites: # List of endpoints to track
  - name: New MasterTopik
    url: https://www.mastertopik.com
status-website: # Status website (optional)
  baseUrl: /mtr # where "repo" is your repository name
  name: MasterTopik Uptime
